//! Renders snippet rows into the expansion engine's match-file dialect (the engine is a GPL
//! fork — see NOTICES.md; the dialect is documented by the upstream project).
//!
//! Match-file shape:
//! ```yaml
//! matches:
//!   - trigger: ":sig"
//!     replace: "Best,\nAsad"
//!   - trigger: ":date"
//!     replace: "It is {{mytime}}"
//!     vars:
//!       - name: mytime
//!         type: date
//!         params: { format: "%H:%M" }
//! ```
//! The `variables` column already holds the engine's `vars` array as JSON, so it maps 1:1.

use serde_yaml::{Mapping, Value};

use crate::{Result, Snippet};

const HEADER: &str = "# AUTO-GENERATED by Glyphio from its SQLite snippet store. DO NOT EDIT BY HAND —\n\
# any manual change is overwritten on the next snippet edit. Manage snippets in the Glyphio app.\n";

/// Serialize live snippets into an engine `match` YAML document (with a do-not-edit header).
///
/// The body key is chosen by `format`: `plain`→`replace`, `markdown`→`markdown`, `html`→`html`.
/// The engine injects markdown/html as rich text via the clipboard (auto plaintext fallback),
/// so retaining formatting on paste is native — no bespoke mechanism.
pub fn render_matches_yaml(snippets: &[Snippet]) -> Result<String> {
    let mut matches = Vec::with_capacity(snippets.len());
    for s in snippets {
        let mut m = Mapping::new();
        m.insert(Value::from("trigger"), Value::from(s.trigger.clone()));
        let body_key = match s.format.as_str() {
            "markdown" => "markdown",
            "html" => "html",
            _ => "replace",
        };
        m.insert(Value::from(body_key), Value::from(s.replacement.clone()));
        if let Some(vars) = &s.variables {
            // JSON var array -> YAML value (serde_json::Value implements Serialize).
            m.insert(Value::from("vars"), serde_yaml::to_value(vars)?);
        }
        matches.push(Value::Mapping(m));
    }
    let mut root = Mapping::new();
    root.insert(Value::from("matches"), Value::Sequence(matches));
    Ok(format!("{HEADER}{}", serde_yaml::to_string(&Value::Mapping(root))?))
}

/// An `app_scope` string parsed into an engine app-config filter.
///
/// Formats (documented in the snippet editor UI):
/// * `exec:<regex>`  — raw regex against the focused app's executable path.
/// * `title:<regex>` — raw regex against the focused window title.
/// * anything else   — case-insensitive substring match against the executable path
///                     (e.g. `Slack` scopes to Slack).
pub(crate) fn scope_filter(scope: &str) -> (&'static str, String) {
    if let Some(re) = scope.strip_prefix("exec:") {
        ("filter_exec", re.to_string())
    } else if let Some(re) = scope.strip_prefix("title:") {
        ("filter_title", re.to_string())
    } else {
        ("filter_exec", format!("(?i){}", regex_escape(scope)))
    }
}

/// Render the engine app-specific config that activates one scoped match file. App configs
/// inherit `default.yml`; `extra_includes` adds the underscore-prefixed match file that the
/// default include glob (`[!_]*.yml`) deliberately skips.
pub(crate) fn render_app_config_yaml(scope: &str, match_file: &str) -> Result<String> {
    let (key, regex) = scope_filter(scope);
    let mut root = Mapping::new();
    root.insert(Value::from(key), Value::from(regex));
    root.insert(
        Value::from("extra_includes"),
        Value::Sequence(vec![Value::from(format!("../match/{match_file}"))]),
    );
    Ok(format!("{HEADER}{}", serde_yaml::to_string(&Value::Mapping(root))?))
}

/// Escape regex metacharacters so a bare scope value matches literally.
fn regex_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        if "\\.^$|?*+()[]{}".contains(c) {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn snippet(trigger: &str, replace: &str, vars: Option<serde_json::Value>) -> Snippet {
        with_format(trigger, replace, vars, "plain")
    }

    fn with_format(trigger: &str, replace: &str, vars: Option<serde_json::Value>, format: &str) -> Snippet {
        Snippet {
            id: "x".into(),
            trigger: trigger.into(),
            replacement: replace.into(),
            format: format.into(),
            variables: vars,
            group_id: None,
            app_scope: None,
            owner: "personal".into(),
            team: None,
            updated_at: "2026-07-01T00:00:00.000Z".into(),
            version: 1,
            deleted_at: None,
        }
    }

    #[test]
    fn rich_formats_emit_markdown_and_html_keys() {
        let out = render_matches_yaml(&[
            with_format(":md", "**bold**", None, "markdown"),
            with_format(":h", "<b>x</b>", None, "html"),
        ])
        .unwrap();
        let parsed: Value = serde_yaml::from_str(&out).unwrap();
        let seq = parsed.get("matches").unwrap().as_sequence().unwrap();
        assert!(seq[0].get("markdown").is_some());
        assert!(seq[0].get("replace").is_none());
        assert!(seq[1].get("html").is_some());
    }

    #[test]
    fn renders_plain_and_var_matches() {
        let out = render_matches_yaml(&[
            snippet(":sig", "Best,\nAsad", None),
            snippet(
                ":date",
                "It is {{mytime}}",
                Some(serde_json::json!([
                    {"name":"mytime","type":"date","params":{"format":"%H:%M"}}
                ])),
            ),
        ])
        .unwrap();

        assert!(out.starts_with("# AUTO-GENERATED"));
        assert!(out.contains("matches:"));
        assert!(out.contains(":sig"));
        assert!(out.contains("replace:"));
        assert!(out.contains(":date"));
        assert!(out.contains("mytime"));
        assert!(out.contains("format:"));

        // Must be parseable back as valid YAML with the expected structure.
        let parsed: Value = serde_yaml::from_str(&out).unwrap();
        let seq = parsed.get("matches").unwrap().as_sequence().unwrap();
        assert_eq!(seq.len(), 2);
        assert!(seq[1].get("vars").is_some());
        assert!(seq[0].get("vars").is_none());
    }

    #[test]
    fn empty_store_renders_empty_matches_list() {
        let out = render_matches_yaml(&[]).unwrap();
        let parsed: Value = serde_yaml::from_str(&out).unwrap();
        assert!(parsed.get("matches").unwrap().as_sequence().unwrap().is_empty());
    }
}
