//! Renders snippet rows into the expansion engine's match-file dialect (the engine is a GPL
//! fork — see NOTICES.md; the dialect is documented by the upstream project).
//!
//! Match-file shape:
//! ```yaml
//! matches:
//!   - trigger: ":sig"
//!     replace: "Best,\nAsad"
//!   - trigger: ":date"
//!     replace: "It is {{mytime}}"
//!     vars:
//!       - name: mytime
//!         type: date
//!         params: { format: "%H:%M" }
//! ```
//! The `variables` column already holds the engine's `vars` array as JSON, so it maps 1:1.

use serde_yaml::{Mapping, Value};

use crate::{Result, Snippet};

const HEADER: &str = "# AUTO-GENERATED by Glyphio from its SQLite snippet store. DO NOT EDIT BY HAND —\n\
# any manual change is overwritten on the next snippet edit. Manage snippets in the Glyphio app.\n";

/// Serialize live snippets into an engine `match` YAML document (with a do-not-edit header).
///
/// The body key is chosen by `format`: `plain`→`replace`, `markdown`→`markdown`, `html`→`html`.
/// The engine injects markdown/html as rich text via the clipboard (auto plaintext fallback),
/// so retaining formatting on paste is native — no bespoke mechanism.
///
/// Kinds beyond plain `text`:
/// * `form` / `popup` — compiled to a single `glyphio_form` / `glyphio_popup` var (the fork's
///   `glyphio` render extension calls back into the app over a unix socket; the app shows the
///   Tauri window and, for forms, returns the filled body).
/// * `command` — compiled to the engine's `shell` var with the body as the command. Rendered
///   **only** for personal snippets (`team` must be NULL; the store enforces that, this is
///   defense in depth) — commands never sync.
/// * `enabled = false` (quarantined / manually off) — not rendered at all.
pub fn render_matches_yaml(snippets: &[Snippet]) -> Result<String> {
    let mut matches = Vec::with_capacity(snippets.len());
    for s in snippets {
        if !s.enabled || (s.kind == "command" && s.team.is_some()) {
            continue;
        }
        let mut m = Mapping::new();
        m.insert(Value::from("trigger"), Value::from(s.trigger.clone()));
        let body_key = match s.format.as_str() {
            "markdown" => "markdown",
            "html" => "html",
            _ => "replace",
        };
        match s.kind.as_str() {
            "popup" => {
                // The app shows the popup window; the var renders to nothing, so the typed
                // trigger simply disappears.
                m.insert(Value::from("replace"), Value::from("{{__glyphio}}"));
                m.insert(
                    Value::from("vars"),
                    serde_yaml::to_value(serde_json::json!([{
                        "name": "__glyphio",
                        "type": "glyphio_popup",
                        "params": { "snippet_id": s.id },
                    }]))?,
                );
            }
            "form" => {
                // The app collects the input and returns the filled body; keeping the
                // snippet's format key means the result still pastes as rich text.
                m.insert(Value::from(body_key), Value::from("{{__glyphio}}"));
                m.insert(
                    Value::from("vars"),
                    serde_yaml::to_value(serde_json::json!([{
                        "name": "__glyphio",
                        "type": "glyphio_form",
                        "params": { "snippet_id": s.id },
                    }]))?,
                );
            }
            "command" => {
                // Engine `shell` extension: body = the command, output pasted verbatim.
                // Options (e.g. {"shell":"bash"}) ride in the `variables` JSON object.
                let mut params = serde_json::json!({ "cmd": s.replacement });
                if let Some(shell) = s.variables.as_ref().and_then(|v| v.get("shell")) {
                    params["shell"] = shell.clone();
                }
                m.insert(Value::from("replace"), Value::from("{{__glyphio}}"));
                m.insert(
                    Value::from("vars"),
                    serde_yaml::to_value(serde_json::json!([{
                        "name": "__glyphio",
                        "type": "shell",
                        "params": params,
                    }]))?,
                );
            }
            _ => {
                m.insert(Value::from(body_key), Value::from(s.replacement.clone()));
                if let Some(vars) = &s.variables {
                    // JSON var array -> YAML value (serde_json::Value implements Serialize).
                    m.insert(Value::from("vars"), serde_yaml::to_value(vars)?);
                }
            }
        }
        matches.push(Value::Mapping(m));
    }
    let mut root = Mapping::new();
    root.insert(Value::from("matches"), Value::Sequence(matches));
    Ok(format!("{HEADER}{}", serde_yaml::to_string(&Value::Mapping(root))?))
}

/// An `app_scope` string parsed into an engine app-config filter.
///
/// Formats (documented in the snippet editor UI):
/// * `exec:<regex>`  — raw regex against the focused app's executable path.
/// * `title:<regex>` — raw regex against the focused window title.
/// * anything else   — case-insensitive substring match against the executable path
///                     (e.g. `Slack` scopes to Slack).
pub(crate) fn scope_filter(scope: &str) -> (&'static str, String) {
    if let Some(re) = scope.strip_prefix("exec:") {
        ("filter_exec", re.to_string())
    } else if let Some(re) = scope.strip_prefix("title:") {
        ("filter_title", re.to_string())
    } else {
        ("filter_exec", format!("(?i){}", regex_escape(scope)))
    }
}

/// Render the engine app-specific config that activates one scoped match file. App configs
/// inherit `default.yml`; `extra_includes` adds the underscore-prefixed match file that the
/// default include glob (`[!_]*.yml`) deliberately skips.
pub(crate) fn render_app_config_yaml(scope: &str, match_file: &str) -> Result<String> {
    let (key, regex) = scope_filter(scope);
    let mut root = Mapping::new();
    root.insert(Value::from(key), Value::from(regex));
    root.insert(
        Value::from("extra_includes"),
        Value::Sequence(vec![Value::from(format!("../match/{match_file}"))]),
    );
    Ok(format!("{HEADER}{}", serde_yaml::to_string(&Value::Mapping(root))?))
}

/// Escape regex metacharacters so a bare scope value matches literally.
fn regex_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        if "\\.^$|?*+()[]{}".contains(c) {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn snippet(trigger: &str, replace: &str, vars: Option<serde_json::Value>) -> Snippet {
        with_format(trigger, replace, vars, "plain")
    }

    fn with_format(trigger: &str, replace: &str, vars: Option<serde_json::Value>, format: &str) -> Snippet {
        Snippet {
            id: "x".into(),
            trigger: trigger.into(),
            replacement: replace.into(),
            format: format.into(),
            kind: "text".into(),
            enabled: true,
            variables: vars,
            group_id: None,
            app_scope: None,
            owner: "personal".into(),
            team: None,
            updated_at: "2026-07-01T00:00:00.000Z".into(),
            version: 1,
            deleted_at: None,
        }
    }

    fn with_kind(trigger: &str, body: &str, kind: &str) -> Snippet {
        Snippet { kind: kind.into(), ..with_format(trigger, body, None, "plain") }
    }

    #[test]
    fn rich_formats_emit_markdown_and_html_keys() {
        let out = render_matches_yaml(&[
            with_format(":md", "**bold**", None, "markdown"),
            with_format(":h", "<b>x</b>", None, "html"),
        ])
        .unwrap();
        let parsed: Value = serde_yaml::from_str(&out).unwrap();
        let seq = parsed.get("matches").unwrap().as_sequence().unwrap();
        assert!(seq[0].get("markdown").is_some());
        assert!(seq[0].get("replace").is_none());
        assert!(seq[1].get("html").is_some());
    }

    #[test]
    fn renders_plain_and_var_matches() {
        let out = render_matches_yaml(&[
            snippet(":sig", "Best,\nAsad", None),
            snippet(
                ":date",
                "It is {{mytime}}",
                Some(serde_json::json!([
                    {"name":"mytime","type":"date","params":{"format":"%H:%M"}}
                ])),
            ),
        ])
        .unwrap();

        assert!(out.starts_with("# AUTO-GENERATED"));
        assert!(out.contains("matches:"));
        assert!(out.contains(":sig"));
        assert!(out.contains("replace:"));
        assert!(out.contains(":date"));
        assert!(out.contains("mytime"));
        assert!(out.contains("format:"));

        // Must be parseable back as valid YAML with the expected structure.
        let parsed: Value = serde_yaml::from_str(&out).unwrap();
        let seq = parsed.get("matches").unwrap().as_sequence().unwrap();
        assert_eq!(seq.len(), 2);
        assert!(seq[1].get("vars").is_some());
        assert!(seq[0].get("vars").is_none());
    }

    #[test]
    fn empty_store_renders_empty_matches_list() {
        let out = render_matches_yaml(&[]).unwrap();
        let parsed: Value = serde_yaml::from_str(&out).unwrap();
        assert!(parsed.get("matches").unwrap().as_sequence().unwrap().is_empty());
    }

    #[test]
    fn popup_and_form_compile_to_glyphio_vars() {
        let mut form = with_kind(":f", "Hi {{name}}", "form");
        form.format = "html".into();
        let out = render_matches_yaml(&[with_kind(":p", "<b>cheatsheet</b>", "popup"), form]).unwrap();
        let parsed: Value = serde_yaml::from_str(&out).unwrap();
        let seq = parsed.get("matches").unwrap().as_sequence().unwrap();

        // Popup: empty replacement via the extension var; body never reaches the engine.
        assert_eq!(seq[0].get("replace").unwrap().as_str(), Some("{{__glyphio}}"));
        let v0 = &seq[0].get("vars").unwrap().as_sequence().unwrap()[0];
        assert_eq!(v0.get("type").unwrap().as_str(), Some("glyphio_popup"));
        assert_eq!(v0["params"]["snippet_id"].as_str(), Some("x"));
        assert!(!out.contains("cheatsheet"));

        // Form keeps the snippet's rich body key so the result pastes formatted.
        assert_eq!(seq[1].get("html").unwrap().as_str(), Some("{{__glyphio}}"));
        let v1 = &seq[1].get("vars").unwrap().as_sequence().unwrap()[0];
        assert_eq!(v1.get("type").unwrap().as_str(), Some("glyphio_form"));
    }

    #[test]
    fn command_compiles_to_shell_var_only_when_personal() {
        let mut cmd = with_kind(":ip", "curl -s ifconfig.me", "command");
        cmd.variables = Some(serde_json::json!({ "shell": "bash" }));
        let out = render_matches_yaml(&[cmd.clone()]).unwrap();
        let parsed: Value = serde_yaml::from_str(&out).unwrap();
        let m = &parsed.get("matches").unwrap().as_sequence().unwrap()[0];
        let v = &m.get("vars").unwrap().as_sequence().unwrap()[0];
        assert_eq!(v.get("type").unwrap().as_str(), Some("shell"));
        assert_eq!(v["params"]["cmd"].as_str(), Some("curl -s ifconfig.me"));
        assert_eq!(v["params"]["shell"].as_str(), Some("bash"));

        // A team'd command record (must not exist, defense in depth) is never rendered.
        cmd.team = Some("sec".into());
        let out = render_matches_yaml(&[cmd]).unwrap();
        let parsed: Value = serde_yaml::from_str(&out).unwrap();
        assert!(parsed.get("matches").unwrap().as_sequence().unwrap().is_empty());
    }

    #[test]
    fn disabled_snippets_are_not_rendered() {
        let mut s = with_kind(":q", "quarantined", "text");
        s.enabled = false;
        let out = render_matches_yaml(&[s]).unwrap();
        let parsed: Value = serde_yaml::from_str(&out).unwrap();
        assert!(parsed.get("matches").unwrap().as_sequence().unwrap().is_empty());
    }
}
