//! The whole platform surface of clipboard history, in one file.
//!
//! Reading and writing clipboard *content* is already cross-platform (the Tauri clipboard
//! plugin), so only four things differ per OS, and each is a handful of lines:
//!
//! | | macOS | Windows |
//! |---|---|---|
//! | has it changed? | `NSPasteboard.changeCount` | `GetClipboardSequenceNumber` |
//! | don't record this | `org.nspasteboard.ConcealedType` | `ExcludeClipboardContentFromMonitorProcessing` |
//! | who copied it | `NSWorkspace.frontmostApplication` | `GetForegroundWindow` → module name |
//! | paste it | ⌘V via `CGEvent` | ^V via `SendInput` |
//!
//! Keeping the seam this narrow is the point: the store, retention, dedupe, search and UI
//! above it are shared, so the Windows port is this file and nothing else.
//!
//! **The Windows half is written but has never been compiled or run** — there is no Windows
//! machine in the loop yet. It is here so the port is a matter of building and fixing, not
//! designing. See `docs/WINDOWS.md`.

/// A monotonic counter that changes when, and only when, the clipboard does. Cheap enough to
/// poll — which is the point, since neither OS offers a notification worth the machinery.
pub fn change_counter() -> i64 {
    #[cfg(target_os = "macos")]
    {
        use objc2_app_kit::NSPasteboard;
        NSPasteboard::generalPasteboard().changeCount() as i64
    }
    #[cfg(target_os = "windows")]
    {
        // SAFETY: no arguments, no failure mode; returns 0 if the caller lacks clipboard access.
        unsafe { windows_sys::Win32::System::DataExchange::GetClipboardSequenceNumber() as i64 }
    }
    #[cfg(not(any(target_os = "macos", target_os = "windows")))]
    {
        0
    }
}

/// Whether whoever put this on the clipboard asked for it not to be recorded.
///
/// Password managers mark their payload, and honouring that is not optional: it is the one
/// convention that keeps a clipboard manager from being a credential logger. macOS uses the
/// `org.nspasteboard.*` types agreed between pasteboard tools; Windows has a registered
/// format meaning the same thing. Unknown or unreadable clipboards count as concealed —
/// the safe answer when we can't tell.
pub fn is_concealed() -> bool {
    #[cfg(target_os = "macos")]
    {
        use objc2_app_kit::NSPasteboard;
        // Also skip content marked transient or auto-generated: it was never meant to
        // outlive the moment, and recording it is how a history fills up with noise.
        const SKIP: [&str; 4] = [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
            "com.agilebits.onepassword",
        ];
        let pb = NSPasteboard::generalPasteboard();
        let Some(types) = pb.types() else { return true };
        types.iter().any(|t| {
            let t = t.to_string();
            SKIP.iter().any(|s| t == *s)
        })
    }
    #[cfg(target_os = "windows")]
    {
        use windows_sys::Win32::System::DataExchange::{
            IsClipboardFormatAvailable, RegisterClipboardFormatW,
        };
        // Both spellings are in the wild: the documented one and the one Chromium registers.
        for name in [
            "ExcludeClipboardContentFromMonitorProcessing\0",
            "CanIncludeInClipboardHistory\0",
        ] {
            let wide: Vec<u16> = name.encode_utf16().collect();
            // SAFETY: `wide` is NUL-terminated for the length of the call.
            let fmt = unsafe { RegisterClipboardFormatW(wide.as_ptr()) };
            if fmt != 0 && unsafe { IsClipboardFormatAvailable(fmt) } != 0 {
                return true;
            }
        }
        false
    }
    #[cfg(not(any(target_os = "macos", target_os = "windows")))]
    {
        false
    }
}

/// The application that currently has focus — the one that almost certainly did the copying.
/// Only used to match the ignore list, and an empty answer simply matches nothing.
pub fn foreground_app() -> String {
    #[cfg(target_os = "macos")]
    {
        objc2_app_kit::NSWorkspace::sharedWorkspace()
            .frontmostApplication()
            .and_then(|a| a.localizedName())
            .map(|n| n.to_string())
            .unwrap_or_default()
    }
    #[cfg(not(target_os = "macos"))]
    {
        String::new()
    }
}

/// Send the paste keystroke to whatever now has focus.
///
/// Putting an item back on the clipboard is only half of "pick it from the list" — the other
/// half is the keystroke the user would otherwise type themselves. The caller is responsible
/// for having stepped out of the way first; see `commands::clipboard_paste`.
pub fn send_paste() -> anyhow::Result<()> {
    #[cfg(target_os = "macos")]
    {
        use core_graphics::event::{CGEvent, CGEventFlags, CGEventTapLocation};
        use core_graphics::event_source::{CGEventSource, CGEventSourceStateID};
        const V: u16 = 9; // kVK_ANSI_V
        let source = CGEventSource::new(CGEventSourceStateID::CombinedSessionState)
            .map_err(|_| anyhow::anyhow!("could not create an event source"))?;
        for down in [true, false] {
            let event = CGEvent::new_keyboard_event(source.clone(), V, down)
                .map_err(|_| anyhow::anyhow!("could not create the paste keystroke"))?;
            event.set_flags(CGEventFlags::CGEventFlagCommand);
            event.post(CGEventTapLocation::HID);
        }
        Ok(())
    }
    #[cfg(target_os = "windows")]
    {
        use windows_sys::Win32::UI::Input::KeyboardAndMouse::{
            SendInput, INPUT, INPUT_KEYBOARD, KEYBDINPUT, KEYEVENTF_KEYUP, VK_CONTROL, VK_V,
        };
        fn key(vk: u16, up: bool) -> INPUT {
            let mut input: INPUT = unsafe { std::mem::zeroed() };
            input.r#type = INPUT_KEYBOARD;
            input.Anonymous.ki = KEYBDINPUT {
                wVk: vk,
                wScan: 0,
                dwFlags: if up { KEYEVENTF_KEYUP } else { 0 },
                time: 0,
                dwExtraInfo: 0,
            };
            input
        }
        let inputs = [
            key(VK_CONTROL, false),
            key(VK_V, false),
            key(VK_V, true),
            key(VK_CONTROL, true),
        ];
        // SAFETY: a well-formed array of INPUT of the size we declare.
        let sent = unsafe {
            SendInput(
                inputs.len() as u32,
                inputs.as_ptr(),
                std::mem::size_of::<INPUT>() as i32,
            )
        };
        if sent as usize != inputs.len() {
            anyhow::bail!("the paste keystroke was blocked");
        }
        Ok(())
    }
    #[cfg(not(any(target_os = "macos", target_os = "windows")))]
    {
        anyhow::bail!("pasting is not implemented on this platform")
    }
}

/// Whether [`send_paste`] can work at all. On macOS synthetic keystrokes need the
/// Accessibility grant — the same one scrolling capture and the expansion engine use, so a
/// working Glyphio already has it.
pub fn can_send_paste() -> bool {
    #[cfg(target_os = "macos")]
    {
        crate::capture::scroll::app_accessibility_trusted()
    }
    #[cfg(not(target_os = "macos"))]
    {
        true
    }
}
